### ISSUE TITLE
console.log in current version

### ISSUE THREAD

**Issue by SvenSchoene** [zimocode/smartup#132]
There are multiple `console.log()`-statements in the current production version, and, especially annoying, every keypress causes a `console.log()`.

E.g.:

https://github.com/zimocode/smartup/blob/master/js/event.js#L69
https://github.com/zimocode/smartup/blob/master/js/event.js#L152

I know that this is just a harmless oversight with disabling dev mode for the current release (e.g.: https://github.com/zimocode/smartup/blob/master/js/event.js#L42). But it's still a very annoying issue. I thought my own code had weird `console.log()`-statements at first.

![smartupgestures_consolelog](https://user-images.githubusercontent.com/7631673/109870063-f04e3680-7c69-11eb-820b-08a9100a9999.png)

**Comment by StrivingRabbit** [comment]
So did I. It was annoying

**Comment by Germxu** [comment]
Yeah, as a developer, it is so annoying, even if without devMode.
So is it why becomes (Beta)?
If there will be a config for whitelist also be OK.

还是非常感谢您的作品 !

**Comment by jinliming2** [comment]
https://github.com/zimocode/smartup/blame/dev/js/event.js#L152

Looks like this comes from a commit 3 years ago, but never worked.

Disable option: `General` -> `Settings` -> `Press [ESC] to cancel current operation`, keycode logs are gone, but still got some `{type: "status"}`s.

**Comment by dcts** [comment]
having the same issue. Was developping an app and deliberately searching for console logs in my code, but didnt find any. Then realized that it is caused by smartUp gestures.

Please fix this fast if possible, it should be easy just deleting the console logs, right? :) 

Love the extension, its been one of the best productivity boosters! And would hate to turn it off just for this weird bug. 

for me @jinliming2 's solution did not work. The console logs still are there, no matter if i change pre ESC setting or no motter if I press ESC.

**Comment by zimocode** [comment]
I made a mistake, uploaded the dev version.
uploaded a new version.
