### ISSUE TITLE
gone from chrome webstore, what happened?

### ISSUE THREAD

**Issue by thoastbrot** [zimocode/smartup#166]
404, chrome disables extension (can be reenabled)...

**Comment by cj233cj** [comment]
https://github.com/zimocode/smartup/issues/110

might be something about ads

**Comment by blue2018** [comment]
Hope it will be back...

**Comment by os9sur** [comment]
Malicious code？

**Comment by shaoran** [comment]
It's a shame, I've been using this extension for ages.

**Comment by zimocode** [comment]
![154918](https://user-images.githubusercontent.com/29518677/134867476-23f35cf8-0227-455b-829f-ef8e58756618.png)

**Comment by thoastbrot** [comment]
wow, due to a missing documentation...

**Comment by yueliangcao** [comment]
> wow, due to a missing documentation...
那就没问题了，很快就回来了。

**Comment by shaoran** [comment]
What does *Violation reference ID: Purple Nickle* mean?

**Comment by random-un** [comment]
> #110
> 
> might be something about ads

Has this extension monetized user data since at least July 2020?? Extremely disappointing if true.

I considered Chrome extensions on github to be more likely to focus on user privacy, but that might not be the case when even popular github projects like [The Great Suspender](https://github.com/greatsuspender/thegreatsuspender) have also been [removed from the Chrome store](https://www.bleepingcomputer.com/news/security/the-great-suspender-chrome-extensions-fall-from-grace/).

**Comment by Rex000** [comment]
Been using this addon for a while. @zimocode will you be adding the said privacy policy so that your addon gets re-enabled by Google?

**Comment by zimocode** [comment]
![image](https://user-images.githubusercontent.com/29518677/135040053-f0b603e4-2e63-4fa2-b523-d934e65c9df3.png)

it's OK
