### ISSUE TITLE
Clipboard related function not working in Firefox

### ISSUE THREAD

**Issue by shigure32** [zimocode/smartup#72]
After I select copy link / copy text function in Easy Drag, SmartUp asks for clipboard permission, yet the function is not working after Firefox is restarted.

Firefox ver: 71.0 64-bit
System: Windows 10 64-bit
SmartUp ver: latest version in Firefox add-on store

**Comment by YandLiu** [comment]
Hi, since the developer hasn't given any reply for a long time, I just uploaded and signed my fixed version, you can use this before the developer fixes it officially. Just need to rename the "zip" to "xpi" and install it.
[smartup-6.5.1348.1026.fixed.zip](https://github.com/zimocode/smartup/files/4133988/smartup-6.5.1348.1026.fixed.zip)



Or you can fix it on your own:
1. Download the xpi file from AMO.
2. Unzip it like a zip file.
3. Open `folder where you unzip`/js/background.js, locate the 1637th line
4. Change`document.execCommand('copy', false, null);` to `document.execCommand('copy', false, null);`
5. Re-pack, upload and sign it on https://addons.mozilla.org/en-US/developers/
